[target.aarch64-apple-darwin]
rustflags = [
"-C", "link-arg=-undefined",
"-C", "link-arg=dynamic_lookup",
'-L /opt/homebrew/opt/libpq/lib -L /opt/homebrew/lib']


[target.stable-x86_64-pc-windows-msvc]
rustflags = [
"-C", "link-arg=-undefined",
"-C", "link-arg=dynamic_lookup",
'-L C:\\Program Files\\MySQL\\MySQL-Connector-C-6.1\\lib\\vs14']
# [target.stable-x86_64-pc-windows-msvc]
# rustc-link-search = ["C:\\Program Files\\PostgreSQL\\15\\lib"]
# rustc-link-lib = ["libpq"]
[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-arg=-Wl,-Bstatic",
  "-C", "link-arg=-Wl,-Bdynamic",
]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

