static_config:
  log_level: info
services:
  - listen_port: 8084
    service_config:
      server_type: http
      route_configs:
        - matcher:
            prefix: /
            prefix_rewrite: /
          router: http://192.168.0.0:9393
