servers:
  - listen: 8082
    protocol: http
    routes:
      - route_id: test_route
        forward_to:
          kind: poll
          targets:
            - endpoint: http://127.0.0.1:9394
            - endpoint: http://127.0.0.1:9395
            - endpoint: http://127.0.0.1:9396
