log_level: info
servers:
  - listen: 8084
    protocol: http
    routes:
      - route_id: test_route
        forward_to:
          kind: headerBased
          routes:
            - base_route:
                endpoint: http://127.0.0.1:9395
              header_key: test
              header_value_mapping_type:
                kind: Text
                value: test
            - base_route:
                endpoint: http://127.0.0.1:9396
              header_key: test
              header_value_mapping_type:
                kind: Text
                value: test
            - base_route:
                endpoint: http://127.0.0.1:9397
              header_key: test
              header_value_mapping_type:
                kind: Text
                value: test
