log_level: info
servers:
  - listen: 8084
    protocol: http
    routes:
      - matcher:
          prefix: /
          prefix_rewrite: /
        forward_to:
          kind: weightBased
          routes:
            - base_route:
                endpoint: http://127.0.0.1:9394
              weight: 1
            - base_route:
                endpoint: http://127.0.0.1:9396
              weight: 2
            - base_route:
                endpoint: http://127.0.0.1:9395
              weight: 3
