static_config:
  log_level: debug
services:
  - listen_port: 4486
    service_config:
      server_type: Http
      routes:
        - matcher:
            prefix: /
            prefix_rewrite: /
          route_cluster:
            type: randomRoute
            routes:
              - base_route:
                  endpoint: http://localhost:6666/
          health_check:
            type: HttpGet
            base_health_check_param:
              timeout: 10
              interval: 10
            path: /health
          liveness_config:
            min_liveness_count: 1
  - listen_port: 9969
    service_config:
      server_type: Http
      routes:
        - matcher:
            prefix: /
            prefix_rewrite: /
          route_cluster:
            type: WeightBased
            routes:
              - base_route:
                  endpoint: http://localhost:8888/
                weight: 1
              - base_route:
                  endpoint: http://localhost:9999/
                weight: 2
              - base_route:
                  endpoint: http://localhost:7777/
                weight: 3
          health_check:
            type: HttpGet
            base_health_check_param:
              timeout: 5
              interval: 5
            path: /health
          liveness_config:
            min_liveness_count: 1
