static_config:
  log_level: debug
services:
  - listen_port: 4486
    service_config:
      server_type: Http
      routes:
        - matcher:
            prefix: /
            prefix_rewrite: /
          route_cluster:
            type: randomRoute
            routes:
              - base_route:
                  endpoint: http://localhost:7777/
                  try_file: null
  - listen_port: 9969
    service_config:
      server_type: Http
      routes:
        - matcher:
            prefix: /
            prefix_rewrite: /
          route_cluster:
            type: HeaderBased
            routes:
              - base_route:
                  endpoint: http://localhost:8888/
                header_key: lsk
                header_value_mapping_type:
                  type: Text
                  value: user-agent
              - base_route:
                  endpoint: http://localhost:9999/
                header_key: lska
                header_value_mapping_type:
                  type: Text
                  value: user-agent
              - base_route:
                  endpoint: http://localhost:7777/
                header_key: lskb
                header_value_mapping_type:
                  type: Text
                  value: user-agent
