static_config:
  log_level: debug
services:
  - listen_port: 4486
    service_config:
      server_type: Http
      routes:
        - matcher:
            prefix: /
            prefix_rewrite: /
          route_cluster:
            type: randomRoute
            routes:
              - base_route:
                  endpoint: http://localhost:7777/
                  try_file: null
  - listen_port: 9969
    service_config:
      server_type: Http
      routes:
        - matcher:
            prefix: /
            prefix_rewrite: /
          route_cluster:
            type: WeightBased
            routes:
              - base_route:
                  endpoint: http://localhost:8888/
                weight: 1
              - base_route:
                  endpoint: http://localhost:9999/
                weight: 2
              - base_route:
                  endpoint: http://localhost:7777/
                weight: 3
