services:
  - listen_port: 8084
    service_config:
      server_type: Http
      routes:
        - route_id: test_route
          matcher:
            prefix: /
            prefix_rewrite: /
          route_cluster:
            type: WeightBased
            routes:
              - base_route:
                  endpoint: http://127.0.0.1:8090
                weight: 1
