services:
  - listen_port: 8084
    service_config:
      server_type: Http
      routes:
        - route_id: test_route
          matcher:
            prefix: /
            prefix_rewrite: /
          router: 192.168.0.0
