static_config:
  log_level: info
services:
  - listen_port: 8084
    service_config:
      server_type: Http
      routes:
        - route_id: test_route
          matcher:
            prefix: /
            prefix_rewrite: /
          router:
            type: file
            doc_root: D:\code\github\gitstats\kvrocks
          middlewares:
            - type: headers
              content:
                type: file
                expires: 24h
                extensions: [js, css, html, png, jpg, gif]
