version: "3.9"

services:
  hey:
    image: demisto/rakyll-hey:1.0.0.44140
    container_name: hey
    tty: true
    deploy:
      resources:
        limits:
          cpus: "12.0"
          memory: 8192M
  backend:
    image: ghcr.io/lsk569937453/echo-server:0.0.5
    container_name: backend
    ports:
      - "9394:80"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
