version: "3.9"
services:
  test:
    image: demisto/rakyll-hey:1.0.0.44140
    tty: true
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
  backend:
    image: ghcr.io/lsk569937453/echo-server:0.0.5
    container_name: backend
    ports:
      - "9394:80"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
  envoy:
    image: envoyproxy/envoy:v1.22.8
    ports:
      - "8050:8050"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
