version: "3.9"

services:
  test:
    image: demisto/rakyll-hey:1.0.0.44140
    container_name: hey
    tty: true
    deploy:
      resources:
        limits:
          cpus: "12.0"
          memory: 8192M
  backend:
    image: ghcr.io/lsk569937453/echo-server:0.0.5
    container_name: backend
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
  hyper-test:
    # image: ghcr.io/lsk569937453/spire:0.0.20
    image: lsk569937453/hyper-test:0.0.1
    container_name: hyper
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
