services:
  - listen_port: 6667
    service_config:
      server_type: Http
      routes:
        - matcher:
            prefix: /
            prefix_rewrite: ssss
          route_cluster:
            type: randomRoute
            routes:
              - base_route:
                  endpoint: http://backend:80/
                  try_file: null
