name: CI (OSX)

on: [push, pull_request]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.72.0
          # - stable
          # - nightly

    name: ${{ matrix.version }} - x86_64-apple-darwin
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@master

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-x86_64-apple-darwin
          profile: minimal
          override: true

      # - name: Generate Cargo.lock
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: generate-lockfile

      # - name: Cache cargo registry
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.cargo/registry
      #     key: ${{ matrix.version }}-x86_64-apple-darwin-cargo-registry-trimmed-${{ hashFiles('**/Cargo.lock') }}

      # - name: Cache cargo index
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.cargo/git
      #     key: ${{ matrix.version }}-x86_64-apple-darwin-cargo-index-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Run silverwind tests
        timeout-minutes: 40
        continue-on-error: true
        run: |
          cd rust-proxy
          cargo clean
          cargo test

      - name: Build silverwind
        continue-on-error: true
        run: |
          cd rust-proxy
          cargo clean
          cargo build --release

      - uses: actions/upload-artifact@v3
        with:
          name: silverwind
          path: rust-proxy/target/release/silverwind # or path/to/artifactsilverwind
